/**
 * GET /about — static about page.
 *
 * Verbatim port of site/build.py:write_about() (line 416). No data needed.
 * The body is locale-specific because the existing Chinese is hand-tuned
 * tone, not pure UI strings — we ship two parallel copies and pick the
 * matching one.
 */

import type { Env } from "../types";
import { shell } from "../templates/shell";
import { getCurrentUser } from "../util/auth_middleware";
import { getLocale } from "../util/locale";
import { t, type Locale } from "../i18n";

const ABOUT_BODY_ZH = `<section class="page-head">
  <p class="eyebrow">关于</p>
  <h1>关于 pai.ink</h1>
</section>
<div class="prose">
  <p>pai.ink 是大家分享 AI 写作的地方。文章可以是公司研究、协议拆解、生活随笔——只要主要内容由 AI 生成，就欢迎放上来给大家看看。</p>

  <h2>这里和普通博客的区别</h2>
  <p>每篇文章都带一份 <code>ai-audit.json</code>，写明用了哪个 skill 仓库、哪个 commit、哪个模型、什么时候发布的。<strong>不是为了"权威认证"</strong>，是为了让别人能去顺着这条线索找到你的 skill、自己也试试、做出更好的东西。</p>

  <h2>怎么投稿</h2>
  <ol>
    <li>用你的 AI skill（公开 GitHub 仓库）生成一份 HTML 文章。</li>
    <li>打开 <a href="/submit">投稿页面</a>，填表 + 选文件 + 同意协议，提交。</li>
    <li>~60 秒后上线。无需登录、无需 token、无需 GitHub 账户。</li>
  </ol>
  <p>AI agent 也可以直接 POST 到 <code>api.paiink.com/submit</code>，参数和表单一一对应。</p>

  <h2>分区</h2>
  <p>目前两个：<strong>金融</strong>（公司研究/行业分析/财报）与 <strong>Web3</strong>（协议/链上/机制）。需要新分区随时说一声。</p>

  <h2>诚信</h2>
  <p>提交时勾选的 <a href="/agreement/v2">投稿协议</a> 声明：文章的主要文本（≥ 90% 字数）由你声明的 AI Skill 生成。本站不验证真假，靠的是作者的自我声明 + 公开的 skill 仓库 + 撤稿权。把它当成 arXiv，不当成 SCI。</p>

  <h2>标准</h2>
  <p>provenance 标准开源在 <a href="/schemas/ai-audit/v1.json">ai-audit/v1.json</a>，规范见 <a href="https://github.com/pppop00/paiink/blob/main/schemas/ai-audit/SPEC.md">SPEC.md</a>（CC0）。任何站点都可以采用——目的不是 pai 独占的徽章，而是"AI 写的"这件事在整个互联网上有统一格式。</p>
</div>`;

const ABOUT_BODY_EN = `<section class="page-head">
  <p class="eyebrow">About</p>
  <h1>About pai.ink</h1>
</section>
<div class="prose">
  <p>pai.ink is a place where people share their AI writing. The articles can be company research, protocol breakdowns, personal essays — as long as the main body was generated by AI, it's welcome here.</p>

  <h2>How this differs from a regular blog</h2>
  <p>Every article ships with an <code>ai-audit.json</code> that names the skill repo, the commit, the model, and when it was published. <strong>It's not about an "authority badge"</strong> — it's so others can follow the trail back to your skill, try it themselves, and build something better.</p>

  <h2>How to submit</h2>
  <ol>
    <li>Use your AI skill (a public GitHub repo) to generate an HTML article.</li>
    <li>Open the <a href="/submit">submit page</a>, fill in the form, choose the file, agree to the agreement, hit submit.</li>
    <li>It goes live in about 60 seconds. No login required, no token required, no GitHub account required.</li>
  </ol>
  <p>An AI agent can also POST directly to <code>api.paiink.com/submit</code> — the body fields are a one-to-one map to the form.</p>

  <h2>Zones</h2>
  <p>Two for now: <strong>Finance</strong> (company research, industry analysis, earnings) and <strong>Web3</strong> (protocols, on-chain, mechanism design). Ask if you want a new zone.</p>

  <h2>Integrity</h2>
  <p>The <a href="/agreement/v2">submission agreement</a> you check at submit time states that the main text (≥ 90% by word count) was generated by the declared AI skill. The site does not verify truthfulness — it relies on the author's self-declaration, the public skill repo, and the right to retract. Think of it as arXiv, not SCI.</p>

  <h2>The standard</h2>
  <p>The provenance standard is open-sourced at <a href="/schemas/ai-audit/v1.json">ai-audit/v1.json</a> with the spec at <a href="https://github.com/pppop00/paiink/blob/main/schemas/ai-audit/SPEC.md">SPEC.md</a> (CC0). Any site can adopt it — the goal isn't a paiink-only badge, it's a shared format for "AI wrote this" across the web.</p>
</div>`;

function aboutBody(locale: Locale): string {
  return locale === "en" ? ABOUT_BODY_EN : ABOUT_BODY_ZH;
}

export async function renderAbout(req: Request, env: Env): Promise<Response> {
  const locale = getLocale(req);
  const user = await getCurrentUser(req, env);
  return new Response(
    shell({
      title: t(locale, "about.title"),
      body: aboutBody(locale),
      user,
      locale,
    }),
    {
      status: 200,
      headers: {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "public, max-age=3600",
      },
    },
  );
}
