/**
 * AUTO-GENERATED by build-assets.mjs. Do not edit by hand.
 *
 * Maps logical asset names to their content-hashed public paths. Use
 * `ASSET_PATHS[name]` everywhere instead of hard-coded `/style.css`
 * so deploys automatically bust browser caches: when the file's bytes
 * change, the hash changes, the URL changes, the cache misses.
 *
 * If TypeScript complains this file is out-of-date, run
 *   node worker/build-assets.mjs
 * or just `wrangler dev` — the [build] hook regenerates it.
 */
export const ASSET_PATHS = {
  "favicon.svg": "/favicon.2d47f2c84d.svg",
  "style.css": "/style.11fdfb20f0.css"
} as const;
