/**
 * R2 helpers — typed wrappers over env.R2_CONTENT.
 *
 * The bucket layout is:
 *   articles/<uuid>/index.html        (raw bytes, never re-serialized)
 *   articles/<uuid>/ai-audit.json     (manifest bytes, never re-serialized)
 *   articles/<uuid>/assets/<name>     (reserved; unused in Phase A)
 *   agreements/agreement-v<N>.md
 *   schemas/ai-audit/v1.json
 *   exports/<uuid>.tar.gz             (lazily generated by /verify export)
 *
 * Important: index.html and ai-audit.json bytes MUST round-trip
 * sha256-identical to what the author submitted. Any helper here that
 * accepts a manifest serializes with the exact same format the original
 * submit handler used (JSON.stringify(m, null, 2) + "\n", see
 * worker/src/index.ts:568) — change only with a full manifest re-hash.
 */

import type { Manifest } from "./types";

// ---------- article HTML ----------

function articleHtmlKey(uuid: string): string {
  return `articles/${uuid}/index.html`;
}

function articleManifestKey(uuid: string): string {
  return `articles/${uuid}/ai-audit.json`;
}

/**
 * Store article HTML bytes. Accepts the raw bytes the submitter sent —
 * never re-encode (would invalidate content_sha256). Both Uint8Array
 * and ArrayBuffer are accepted; both satisfy R2Bucket.put without copy.
 */
export async function putArticleHTML(
  bucket: R2Bucket,
  uuid: string,
  bytes: ArrayBuffer | Uint8Array,
): Promise<void> {
  await bucket.put(articleHtmlKey(uuid), bytes, {
    httpMetadata: {
      contentType: "text/html; charset=utf-8",
    },
  });
}

/**
 * Returns the body stream for the article's index.html, or null if the
 * object doesn't exist. Callers are expected to forward this stream to
 * the client unmodified.
 */
export async function getArticleHTML(
  bucket: R2Bucket,
  uuid: string,
): Promise<ReadableStream | null> {
  const obj = await bucket.get(articleHtmlKey(uuid));
  return obj ? obj.body : null;
}

// ---------- article manifest ----------

const MANIFEST_NEWLINE = "\n";

/** Pretty-printed, trailing-newline JSON — matches the legacy format. */
export function serializeManifest(m: Manifest): string {
  return JSON.stringify(m, null, 2) + MANIFEST_NEWLINE;
}

/**
 * Write a manifest in the canonical byte-stable form. The manifest is
 * what readers verify against — once written, never re-write.
 */
export async function putArticleManifest(
  bucket: R2Bucket,
  uuid: string,
  manifest: Manifest,
): Promise<void> {
  const body = serializeManifest(manifest);
  await bucket.put(articleManifestKey(uuid), body, {
    httpMetadata: {
      contentType: "application/json; charset=utf-8",
    },
  });
}

export async function getArticleManifest(
  bucket: R2Bucket,
  uuid: string,
): Promise<Manifest | null> {
  const obj = await bucket.get(articleManifestKey(uuid));
  if (!obj) return null;
  const text = await obj.text();
  try {
    return JSON.parse(text) as Manifest;
  } catch {
    // Garbled manifest in R2 means a deeper problem; surface as not-found.
    return null;
  }
}

/** Returns the raw bytes of the manifest (preserves byte-stability). */
export async function getArticleManifestBytes(
  bucket: R2Bucket,
  uuid: string,
): Promise<Uint8Array | null> {
  const obj = await bucket.get(articleManifestKey(uuid));
  if (!obj) return null;
  return new Uint8Array(await obj.arrayBuffer());
}

// ---------- static archive (agreements + schema) ----------

function agreementKey(version: string): string {
  return `agreements/agreement-${version}.md`;
}

const SCHEMA_KEY = "schemas/ai-audit/v1.json";

/** Returns the canonical bytes for a pinned agreement version, or null. */
export async function getAgreementBytes(
  bucket: R2Bucket,
  version: string,
): Promise<Uint8Array | null> {
  const obj = await bucket.get(agreementKey(version));
  if (!obj) return null;
  return new Uint8Array(await obj.arrayBuffer());
}

/** Returns the schema mirror bytes, or null if it hasn't been seeded. */
export async function getSchemaBytes(
  bucket: R2Bucket,
): Promise<Uint8Array | null> {
  const obj = await bucket.get(SCHEMA_KEY);
  if (!obj) return null;
  return new Uint8Array(await obj.arrayBuffer());
}
