#!/usr/bin/env node
/**
 * build-assets.mjs — content-hash fingerprinting for static assets.
 *
 * Purpose
 * -------
 * Browsers cache CSS / favicons aggressively. When we deploy a new
 * style.css, users who already have the old one cached keep seeing the
 * old style until their cache TTL expires (sometimes days). The
 * industry-standard fix is to give each asset a content-derived URL
 * (style.<10hex>.css) so when bytes change the URL changes and the
 * browser MUST refetch.
 *
 * What this script does
 * ---------------------
 *   1. Reads every file in `worker/static/`.
 *   2. Hashes its bytes (sha256, first 10 hex chars — collision odds
 *      are 2^-40, plenty for an MVP-scale site).
 *   3. Writes the file into `worker/static-dist/<base>.<hash>.<ext>`.
 *      ALSO emits the un-hashed copy alongside, so any user with stale
 *      cached HTML referencing `/style.css` still gets a (correct)
 *      response and doesn't see a totally unstyled page during the
 *      transition window. The hashed name is canonical; the un-hashed
 *      is best-effort fallback.
 *   4. Writes `worker/src/asset-manifest.ts` exporting a typed
 *      `ASSET_PATHS` map so the Worker can read `ASSET_PATHS["style.css"]`
 *      and get back `/style.<hash>.css`.
 *
 * When it runs
 * ------------
 * wrangler.toml has a `[build] command = "node build-assets.mjs"` block,
 * which makes both `wrangler dev` and `wrangler deploy` invoke this
 * automatically. There's no separate npm script to remember.
 *
 * What's NOT done
 * ---------------
 * No source maps, no minification, no transforms. Static assets stay
 * exactly as authored — content hashing is the whole job.
 */

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(ROOT, "static");
const DIST = path.join(ROOT, "static-dist");
const MANIFEST_TS = path.join(ROOT, "src", "asset-manifest.ts");

const HASH_BYTES = 10;

function hashBytes(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex").slice(0, HASH_BYTES);
}

function walk(dir, basePrefix = "") {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = basePrefix ? `${basePrefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      out.push(...walk(full, rel));
    } else if (entry.isFile()) {
      out.push({ rel, full });
    }
  }
  return out;
}

function hashedName(rel, hash) {
  // Insert .<hash> immediately before the file extension.
  // e.g. "style.css" → "style.<hash>.css"
  //      "fonts/blah.woff2" → "fonts/blah.<hash>.woff2"
  const dot = rel.lastIndexOf(".");
  if (dot < 0 || dot < rel.lastIndexOf("/")) {
    // No extension; just append the hash.
    return `${rel}.${hash}`;
  }
  return `${rel.slice(0, dot)}.${hash}${rel.slice(dot)}`;
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

const manifest = {};
for (const { rel, full } of walk(SRC)) {
  const bytes = fs.readFileSync(full);
  const hash = hashBytes(bytes);
  const hashed = hashedName(rel, hash);

  const distHashed = path.join(DIST, hashed);
  fs.mkdirSync(path.dirname(distHashed), { recursive: true });
  fs.writeFileSync(distHashed, bytes);

  // Transition fallback: also write the un-hashed copy so old cached
  // HTML referencing /style.css still loads a (correct) response.
  const distRaw = path.join(DIST, rel);
  fs.mkdirSync(path.dirname(distRaw), { recursive: true });
  fs.writeFileSync(distRaw, bytes);

  manifest[rel] = `/${hashed}`;
  console.log(`  ${rel} → /${hashed}`);
}

const ts = `/**
 * AUTO-GENERATED by build-assets.mjs. Do not edit by hand.
 *
 * Maps logical asset names to their content-hashed public paths. Use
 * \`ASSET_PATHS[name]\` everywhere instead of hard-coded \`/style.css\`
 * so deploys automatically bust browser caches: when the file's bytes
 * change, the hash changes, the URL changes, the cache misses.
 *
 * If TypeScript complains this file is out-of-date, run
 *   node worker/build-assets.mjs
 * or just \`wrangler dev\` — the [build] hook regenerates it.
 */
export const ASSET_PATHS = ${JSON.stringify(manifest, null, 2)} as const;
`;
fs.writeFileSync(MANIFEST_TS, ts);
console.log(`Wrote ${path.relative(ROOT, MANIFEST_TS)} (${Object.keys(manifest).length} entries)`);
