-- migrate.sql — apply with `npx wrangler d1 execute paiink --remote --file tools/migrate.sql`
-- Generated by tools/migrate_to_d1.py — do not hand-edit; rerun the generator.
--
-- Note: no BEGIN/COMMIT — D1 rejects explicit SQL transactions. wrangler
-- d1 execute already applies the file as a single atomic batch via the D1 API.

-- Founder user. password_hash NULL means "unclaimed"; Phase B signup will set it.
INSERT INTO users (id, email, password_hash, display_name, handle, ui_lang, created_at) VALUES (1, 'oliverun6@gmail.com', NULL, 'Zelong', 'zelong', 'zh-CN', 1778673600);

-- Articles (author_id=1 — all current content is Zelong's).
INSERT INTO articles (
  uuid, zone, slug, language, title, author_id, author_email,
  author_display_name, content_sha256, word_count, license,
  agreement_version, agreement_sha256, skill_name, skill_repo_url,
  skill_repo_commit, model, harness, api_request_id, finished_at,
  published_at
) VALUES (
  '1758990d-d44a-484c-a47d-14240791d048',
  'finance',
  'adm-2026-05-13',
  'zh-CN',
  'Archer Daniels Midland — 权益研究',
  1,
  'oliverun6@gmail.com',
  'Zelong',
  'b19d3a0f0ec346b9adb39da23ffe5b77cd7bbb3f08e4ad845e01a854d8d1a7cb',
  3081,
  'CC-BY-NC-4.0',
  'v1',
  'd89b0a30554743958e704b4d825966fad2eb22b6399bc00d0a15809f8deed807',
  'Anamnesis Research',
  'https://github.com/pppop00/anamnesis-research',
  '53d77d9275e42ff528fe306cd042e560c5e88fdb',
  'claude-opus-4-7',
  'claude-code-cli',
  NULL,
  1778817456,
  1778673600
);

INSERT INTO articles (
  uuid, zone, slug, language, title, author_id, author_email,
  author_display_name, content_sha256, word_count, license,
  agreement_version, agreement_sha256, skill_name, skill_repo_url,
  skill_repo_commit, model, harness, api_request_id, finished_at,
  published_at
) VALUES (
  '9deec278-2fdc-48e4-b122-3cc5c5e2e9df',
  'finance',
  'heico-2026-05-16',
  'zh-CN',
  'HEICO',
  1,
  'oliverun6@gmail.com',
  'Zelong',
  '26c2d06419de2622eca715c1af0c97537157f837bbd6a2caf220426cea14bc5c',
  3115,
  'CC-BY-NC-4.0',
  'v2',
  'ec4066647aad291af1e7e88387b3dbfea8c63fce13da3e5ba64f11299793a19d',
  'Anamnesis Research',
  'https://github.com/pppop00/anamnesis-research',
  'e5238cdbf97cfb9dd9a4f46116065e3ebc129a2a',
  'claude-opus-4-7',
  'claude-code-cli',
  NULL,
  1778897624,
  1778897624
);

INSERT INTO articles (
  uuid, zone, slug, language, title, author_id, author_email,
  author_display_name, content_sha256, word_count, license,
  agreement_version, agreement_sha256, skill_name, skill_repo_url,
  skill_repo_commit, model, harness, api_request_id, finished_at,
  published_at
) VALUES (
  'f48fe562-c17f-404f-ad48-4e1a12b2f258',
  'finance',
  'otis-worldwide-2026-05-15',
  'zh-CN',
  'Otis Worldwide',
  1,
  'oliverun6@gmail.com',
  'Zelong',
  'b2d976d064b193627b150ebeb3b488e8e834cd19e46f97716cd290f73ce03394',
  3069,
  'CC-BY-NC-4.0',
  'v1',
  'd89b0a30554743958e704b4d825966fad2eb22b6399bc00d0a15809f8deed807',
  'Anamnesis Research',
  'https://github.com/pppop00/anamnesis-research',
  'e5238cdbf97cfb9dd9a4f46116065e3ebc129a2a',
  'claude-opus-4-7',
  'claude-code-cli',
  NULL,
  1778874130,
  1778846400
);

INSERT INTO articles (
  uuid, zone, slug, language, title, author_id, author_email,
  author_display_name, content_sha256, word_count, license,
  agreement_version, agreement_sha256, skill_name, skill_repo_url,
  skill_repo_commit, model, harness, api_request_id, finished_at,
  published_at
) VALUES (
  '543b34c7-84e4-4eea-9207-e692ed72c657',
  'finance',
  'waste-management-2026-05-14',
  'zh-CN',
  '废弃物管理（WM）— 权益研究报告',
  1,
  'oliverun6@gmail.com',
  'Zelong',
  'aa43f572dc34986f474b764978e480967e8963d326653c48bca79ba2d9066891',
  3099,
  'CC-BY-NC-4.0',
  'v1',
  'd89b0a30554743958e704b4d825966fad2eb22b6399bc00d0a15809f8deed807',
  'Anamnesis Research',
  'https://github.com/pppop00/anamnesis-research',
  '0000000000000000000000000000000000000000',
  'claude-opus-4-7',
  'claude-code-cli',
  NULL,
  1778814053,
  1778760000
);
